### ISSUE TITLE
Rendre impossible la création d'un tag en double

### ISSUE THREAD

**Issue by johanricher** [fm89/granddebat#1]
En tant qu'utilisateur il peut m'arriver de faire une erreur en annotant une réponse et de créer un tag qui existait déjà. J'aimerais que cette action soit rendue impossible pour éviter la création de doublons inutiles.

**Comment by fm89** [comment]
Merci pour cette remarque ! Désormais, une étape de validation précède la création d'un tag et l'utilisateur est averti lorsqu'il tente de créer une catégorie en double (modulo la casse).
