### ISSUE TITLE
Ne valider les contributions qu'une fois qu'au moins 3 personnes ont choisi les mêmes tags

### ISSUE THREAD

**Issue by Massiliane** [fm89/granddebat#10]
Bien que dans la FAQ il est précisé que : "Par ailleurs, notre objectif à moyen terme est que chaque contribution au grand débat soit analysée par plusieurs personnes différentes. Ainsi, le risque de mauvaise catégorisation d'une contribution sera diminué d'autant. Cette approche a par exemple fait ses preuves pour la numérisation des déclarations d'intérêts des élus."
L'idée de conserver les contributions ayant reçu trois fois les mêmes tags permettrait d'éviter les biais et les interprétations trop subjectives ! 
--> Dans un compte-rendu relatif à un travail similaire, Regards Citoyens, Fais ta loi et Democracy OS avaient relevé que : "Cet exercice a démontré l’extrême difficulté d’extraire des éléments objectifs, à partir des points de vue recueillis. Comme pour nos autres opérations de crowdsourcing, nous avions décidé de valider l’analyse d’une contribution une fois seulement qu’au moins 3 utilisateurs différents l’avaient évalué à l’identique. Malgré notre volonté d’offrir une grille d’analyse la plus objective possible, cette règle n’a cependant permis de valider que 40 % des analyses, du fait de l’extrême difficulté à surmonter les nombreux biais qualitatifs individuels. 80 contributions d’intérêt sur 900 ont tout de même pu être identifiées grâce à cette méthodologie."
https://www.regardscitoyens.org/quelles-garanties-pour-que-les-consultations-citoyennes-aient-des-finalites-democratiques/

**Comment by fm89** [comment]
Merci de votre intérêt pour ce projet et pour ce lien. Nous sommes très intéressés par les retours d'expériences d'autres projets similaires.

Nous allons rapidement mettre en place ce mécanisme de lectures multiples (sous quelques jours au plus) car nous sommes convaincus qu'il est effectivement indispensable. La masse de données est immense, mais il vaut sûrement mieux catégoriser 20% des réponses avec une triple lecture concordante que de viser une lecture exhaustive mais sans redondance. La lecture exhaustive serait symboliquement forte, mais, d'un strict point de vue statistique, une classification de qualité de 20% de la base serait déjà hautement significative et pourrait (qui sait) servir de base d'apprentissage supervisé.

Dans le contexte du grand débat, l'autre option est en effet une analyse par "intelligence artificielle". Le taux de mauvaise classification par celle-ci sera probablement tout aussi élevé que les biais subjectifs d'interprétation d'une lecture humaine.

**Comment by fm89** [comment]
Suite à votre message, nous tenions à vous informer que les lectures multiples sont en cours depuis quelques jours désormais. A chaque nouvelle annotation, une petite routine (voir https://github.com/fm89/granddebat/blob/master/app/Logic/Priority.php) compare les annotations des différents annotateurs pour déterminer s'il faut ou non demander une nouvelle lecture du morceau de texte. On impose de toute façon au moins 3 lectures. Et on abandonne (pour le moment) au bout de 7 lectures qu'on ait convergé ou non (pour éviter que des textes difficiles à comprendre monopolisent les efforts). Nous en sommes actuellement à la 3ème passe de la communauté d'annotateurs sur un grand volume de texte et nous pourrons donc avoir les premiers retours pour voir si, en moyenne, les différents lecteurs ont globalement la même interprétation des textes.

**Comment by Massiliane** [comment]
Super nouvelle ! 
Je pense que le choix de se concentrer sur une partie des contributions plutôt que l'exhaustivité est un choix raisonnable.
Cela serait bien, une fois les analyses terminées de montrer la difficulté de trouver des convergences (ou au contraire la facilité ?).
Bref, bon courage !
