### ISSUE TITLE
Question tags "Aucun"

### ISSUE THREAD

**Issue by Cyrille37** [fm89/granddebat#11]
Je pense que j'ai mal utilisé l'outil:
À la question "Pour quelle(s) politique(s) publique(s) ou pour quels domaines d'action publique, seriez-vous prêts à payer plus d'impôts ?" 
Pour une réponse "J'ai toujours payé des impôts depuis le début de ma vie professionnelle, et je trouve cela normal, c'est la logique du travail=salaire, hors de question d'être plus taxé, que les évasions fiscales soient punies"
J'ai sélectionné les tags "Aucun" et "Lutte fraude", pour refléter au mieux la réponse. Mais ça peut être faux en fonction de la méthode d'analyse ...
Un avis s'il vous plaît ?

**Comment by fm89** [comment]
Merci d'avoir testé l'outil et en plus en prenant du recul sur son utilisation.

Dans le cas concret que vous évoquez, j'aurais choisi les mêmes catégories. Bien sûr, la réduction d'un texte libre à un nombre fini de catégories est nécessairement imparfaite. Ici, j'ai l'impression que "Aucun" + "Lutte fraude" résume bien le point de vue du contributeur qui ne souhaite pas payer plus d'impôts et souhaite lutter contre la fraude (l'évasion, l'optimisation).

La catégorie "Lutte fraude" regroupe effectivement aussi des personnes qui seraient prêtes à payer plus d'impôts pour augmenter les budgets de la lutte anti-fraude ; ce qui n'est pas tout à fait la même chose, nous en convenons.

Ce travail collaboratif doit aboutir à une première classification qui pourra faciliter des analyses futures plus fines sur des thématiques précises. Le module de recherche (pour cette question : https://grandeannotation.fr/questions/166/search) permet par exemple de filtrer sur "Lutte fraude" pour se faire une idée des contributions correspondantes.

**Comment by fm89** [comment]
D'un point de vue technique, quand on valide, tous les tags cochés sont enregistrés en base (quel que soit leur sens en français). Quand on utilise la croix, on stocke en base uniquement un tag générique "Sans réponse / Hors sujet / Ne sait pas".

**Comment by Cyrille37** [comment]
Il y a de nombreuses contributions qui dénoncent une mauvaise gestion, ou demande un meilleur gestion, des revenus de l'État. Mais je ne sais pas quel "tag" ajouter ...

**Comment by fm89** [comment]
Bienvenu au club ! Vous pourriez créer "Gérer mieux". Nous avons tenté de limiter les catégories par défaut à des catégories qui désignent une "politique publique ou un domaine d'action publique" (puisque c'était la question, et qu'il y a des espaces entièrement libres plus loin dans le questionnaire). Pour cette question, le tag "Aucun" est effectivement souvent suivi d'un argumentaire expliquant qu'il faut faire mieux avec le niveau d'imposition actuel. Ce n'est pas un "aucun, je suis égoïste" mais plutôt un "aucun, faites mieux avec l'actuel".
