### ISSUE TITLE
"Patientez" suite clic "valider / sans réponse ..."

### ISSUE THREAD

**Issue by Cyrille37** [fm89/granddebat#12]
Il faudrait améliorer la visibilité que l'opération est en cour suite à l'enregistrement (valider/sans réponse ...). Dès fois ça prend 2 à 3 secondes, du coup on ne sait pas ce qu'il se passe.

**Comment by fm89** [comment]
Merci. Effectivement c'était perturbant. Désormais, le bouton se grise avec une légère animation de chargement. Nous allons aussi optimiser certaines requêtes car personne ne devrait attendre 3s !

**Comment by Cyrille37** [comment]
On a pas tous une connexion Internet de qualité. On parle souvent de débit mais la qualité de la connexion (latence et autre) est aussi un désagrément important en campagne avec de l'ADSL de plusieurs kilomètres :-{
Ce que je veux dire c'est que bien que le serveur réponde très rapidement, du côté "client" on aura tout de même un temps de réponse plus long.

**Comment by fm89** [comment]
Vous avez raison. L'affichage côté client indique plus clairement maintenant que la requête a bien été envoyée et qu'on attend son retour.

**Comment by Cyrille37** [comment]
Merci !
