### ISSUE TITLE
Raccourcis clavier

### ISSUE THREAD

**Issue by AntoineAugusti** [fm89/granddebat#15]
La tâche d'annoter est fastidieuse. Un moyen de l'accélérer serait de proposer une meilleure navigation au clavier.

La modification qui a le plus d'impact serait de pouvoir valider les tags choisis rapidement, sans cliquer sur le bouton bleu `Valider`. C'est le composant `Tagger` qui semble être responsable de ceci. Peut-être la touche Entrée ou la touche V ?

**Comment by fm89** [comment]
Excellente idée. Désormais, la touche "Entrée" valide les tags cochés ou opte pour l'option "Sans réponse" si aucun tag n'est sélectionné.

**Comment by AntoineAugusti** [comment]
Merci d'avoir pris le temps de réaliser cette fonctionnalité !
