### ISSUE TITLE
Tag Z Autres

### ISSUE THREAD

**Issue by AntoineAugusti** [fm89/granddebat#16]
Sur la page https://grandeannotation.fr/questions/147, on voit deux tags avec des noms étranges :
- Z Autres
- Z Je ne suis pas touché

Est-ce pour forcer l'affichage en dernier ?

**Comment by fm89** [comment]
C'est l'effet recherché mais les lettres ne devraient effectivement pas apparaître. C'est corrigé.

**Comment by AntoineAugusti** [comment]
Merci d'avoir pris le temps de corriger !
