### ISSUE TITLE
Lisibilité des tag

### ISSUE THREAD

**Issue by romtal** [fm89/granddebat#2]
Les tags n'apparaissent pas de manière lisible...les mots sont coupés...
![tags](https://user-images.githubusercontent.com/15154033/52554807-4da78e80-2de8-11e9-95a3-89ec3eb2eb46.PNG)

**Comment by fm89** [comment]
Normalement, ça devrait être mieux désormais

**Comment by fm89** [comment]
Le module a été entièrement revu depuis cette remarque et les textes ne devraient plus jamais dépasser.

**Comment by romtal** [comment]
Merci :)
