### ISSUE TITLE
Bouton + Créer la catégorie ne marche pas sous IE 11

### ISSUE THREAD

**Issue by marion-paclot** [fm89/granddebat#3]
Il n'est pas possible de créer une nouvelle catégorie (tag) via le bouton + Créer > + Créer la catégorie avec Internet Explorer 11.785

**Comment by fm89** [comment]
Merci pour cette remarque. Désormais, on pallie les insuffisances d'IE11 en important le module nécessaire. Cela devrait fonctionner. (Testé sous IE 11.0).
