### ISSUE TITLE
Pré sélectionner un tag

### ISSUE THREAD

**Issue by Wats0ns** [fm89/granddebat#6]
Hello,
effectivement, il faut bien un humain pour trier les contributions. Par contre si certains tags sont préselectionnés, cela gagnerait du temps.
Exemple: 
Contribution: "Les retraites, le Handicap, l'enfance"
Tags préselectionnés: "Retraité", "Handicap", "Enfance"

**Comment by fm89** [comment]
Bonjour,

Merci beaucoup pour votre intérêt pour ce projet et pour votre idée. Effectivement, une partie des textes pourrait être analysée et classifiée par des scripts. 

Il y a tout de même un risque que la vigilance baisse et que l'humain se contente de valider mécaniquement sans vraiment lire le texte. J'ignore si la qualité globale s'en trouverait améliorée. Je suis preneur d'autres avis.

D'un point de vue technique, je ne sais pas non plus comment déterminer si un texte est "facile" ou "difficile". Il faut gérer la ponctuation, les conjonctions, les légers écarts de frappe, les négations ? Je ne saurais pas bien où m'arrêter. Et c'est justement une des valeurs ajoutées de la lecture humaine.

Peut-être que nous pourrions orienter les humains prioritairement vers les textes les plus longs (même si c'est parfois réconfortant quand on classifie à la main de tomber sur un "facile").

Quoi qu'il en soit, à l'issue du processus manuel, il faudra ou bien confronter les résultats avec ceux de scripts, ou bien utiliser les résultats manuels pour entraîner des modèles automatisées, pour aboutir à une analyse de la meilleure qualité possible et avec la couverture la plus large possible.

**Comment by Wats0ns** [comment]
Hello,
je ne propose pas de trier les annotations par des humains.
L'objectif serait que quand l'humain arrive sur une contribution à annoter comme il le fait actuellement, certains tags soient préselectionnés, et l'humain peut cliquer sur valider s'ils lui conviennent, ou en rajouter/supprimer. L'objectif est de faire gagner du temps aux contributeurs humains

**Comment by oliviernguyenquoc** [comment]
Je suis complètement d'accord et on pourrait arriver à un bon résultat en faisant du machine learning / deep learning à partir de la base déjà annoté. 

Pensez-vous que cela vaille le coup que je me lance la dedans ? Je peux voir pour travailler sur l'idée avec d'autres data scientists. Qu'en pensez-vous ?

Le dataset est hyper intéressant. On peut même regarder si l'on peut détecter des contribution mal labélés ou avec des labels manquants.

Je sais que les auteurs ont l'air de ne pas vouloir trop d'automatisation mais si on se débrouille pour bien controller les résultats, je pense qu'il faut faire une tentative.

**Comment by fm89** [comment]
Bonjour,

Concernant l'analyse automatisée des données du grand débat, il y a déjà eu des débuts de discussion [ici](https://teamopendata.org/t/donnees-du-grand-debat/1079/35) et [là](https://chat.codefor.fr/channel/opendebat) qu'il faut sans doute lire avant de se lancer. C'est évidemment un magnifique jeu de données. Certains d'entre nous sont data-scientists ou même chercheurs et s'y sont déjà essayé avec plaisir.

Nous encourageons toutes les ré-utilisations des données d'annotation de la plateforme [https://grandeannotation.fr](https://grandeannotation.fr). C'est aussi pour cela qu'elles sont ouvertes et mises à jour automatiquement chaque nuit. (Attention toutefois à bien lire les différents avertissements en rouge et à aller lire les liens proposés pour bien comprendre les différents biais avant de foncer tête baissée). Nous serons heureux de relayer, retweeter, promouvoir les analyses faites à partir des annotations manuelles (tant que le code source des analyses et leurs résultats sont aussi ouverts).

Pour des questions de simplicité du message de la plateforme, nous pensons effectivement qu'il faut qu'elle reste pour le moment uniquement dédiée à la lecture par l'humain et l'annotation par l'humain. Mais ça n'empêche pas (bien au contraire), de mener en parallèle des analyses outillées (qu'elles soient autonomes ou reposent sur les annotations manuelles).

Nous vous encourageons à utiliser la plateforme pour annoter quelques centaines de textes à la main (par exemple, y consacrer une heure ou deux). Cela vous donnera un meilleur aperçu du contenu des contributions et de la faisabilité ou non d'une analyse automatique.

Tenez-nous au courant ;-)

**Comment by oliviernguyenquoc** [comment]
Merci beaucoup. Je vais lire tout ca. C'est super interessant.

**Comment by oliviernguyenquoc** [comment]
Je lance le débat sur l'espace de discussion [teamopendata](https://teamopendata.org/t/donnees-du-grand-debat/1079/36?u=olivier_n). Il est bien entendu nécessaire de faire attention aux éventuellement biais. 

Avec une bonne approche et un bon contrôle du résultat. Cela peut peut être donner quelques chose de bien.

**Comment by fm89** [comment]
Après un mois, la plateforme tourne bien sans rien sélectionner par défaut. Bien sûr, il y aurait eu une autre approche tout à fait valable consistant à pré-catégoriser les données avec des outils de traitement du langage, puis à poser des questions simples aux utilisateurs : "Est-ce que ce texte dit bien que ... ?" Ce sera pour la prochaine fois ! Pour cette fois-ci, on va rester sur une approche où toute la compréhension du sens est réservée à l'humain et ou l'ordinateur n'est là que pour les tâches administratives de gestion du processus. Merci pour vos idées !
